(package "flycheck-languagetool"
         "0.3.0"
         "Flycheck support for LanguageTool")

(website-url "https://github.com/emacs-languagetool/flycheck-languagetool")
(keywords "grammar" "check")

(package-file "flycheck-languagetool.el")

(source "melpa")

(depends-on "emacs" "25.1")
(depends-on "flycheck")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
